version: '3'
services:
  db:
    image: mongo:4.0.0
    ports:
    - "27017:27017"
  api:
    build: student/.
    ports:
    - "8080:8080"
    links:
    - db
  frontend:
    build: studentui/.
    ports:
    - "80:80"
    links:
    - api
